---
settings:
  name: BlueXP remediation
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti per la risoluzione dei problemi BlueXP
    url: "/index.html"
  - title: Note di rilascio
    url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sulla soluzione BlueXP
      url: "/concept-resource-templates.html"
    - title: Scopri di più sull'etichettatura
      url: "/concept-tagging.html"
  - title: Utilizzare la soluzione BlueXP
    entries:
    - title: Utilizzare modelli per standardizzare la creazione delle risorse
      entries:
      - title: Creazione di modelli per la tua organizzazione
        url: "/task-define-templates.html"
      - title: Verificare le risorse per la conformità dei modelli
        url: "/task-check-template-compliance.html"
      - title: Eseguire modelli per creare risorse
        url: "/task-run-templates.html"
    - title: Organizzare le risorse utilizzando tag
      entries:
      - title: Gestisci i tag per le tue risorse
        url: "/task-using-tags.html"
  - title: Concetti
    entries:
    - title: Blocchi di base del modello
      url: "/reference-template-building-blocks.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
